# Test only master branch (and PRs).
branches:
  only:
    - master

# Environment configs.
environment:
  nodejs_version: "10"

# Install scripts.
install:
  - ps: Install-Product node $env:nodejs_version

# Test setup scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run setup script
  - powershell -NoProfile -ExecutionPolicy Bypass -file "native-script.ps1" "--silentMode"
  # Install NativeScript
  - npm i -g nativescript --ignore-scripts
  - tns usage-reporting disable
  - tns error-reporting disable
  # Run doctor and build app
  - tns doctor
  - tns create TestApp --js
  - tns build android --path TestApp
     
# Do not build (by default it tries to build .NET projects)
build: off
